name: Subdomain Enumeration Monitor

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual execution

jobs:
  subdomain_enum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y golang
          go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
          export PATH=$PATH:$(go env GOPATH)/bin

      - name: Run Subdomain Monitoring Script
        run: bash monitor_subdomains.sh

      - name: Commit and Push Changes
        if: steps.monitor.outputs.changed == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add subdomains.txt
          git commit -m "Updated subdomains list"
          git push

      - name: Create GitHub Issue if new subdomains are found
        if: steps.monitor.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/issues \
               -d '{"title": "New Subdomains Found", "body": "New subdomains were discovered. Check subdomains.txt for details."}'
